name: Deploy React App to AWS S3 and CloudFront

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to AWS S3
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_MAIN }} --delete
          elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_DEV }} --delete
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront cache
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_MAIN }} --paths "/*"
          elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
            aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_DEV }} --paths "/*"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
